frizzyapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('', views.home, name="home"),
	path("about/", views.about, name="about"),
	path("search/", views.SearchResultsView.as_view(), name="search_shops"),
	path("shops/", views.ShopList.as_view(), name="shop_index"),
	path("shops/<int:shop_id>/", views.shop_details, name="shop_detail"),

	path("profile/", views.profile, name="profile_detail"),
	path('profile/<int:profile_id>/add_creditcard/', views.add_creditcard, name='add_creditcard'),
	# TODO: add profile update using class-based view
	path("profile/<int:pk>/update/", views.ProfileUpdate.as_view(), name="profile_update"),

	path("creditcards/<int:pk>/update/", views.CreditCardUpdate.as_view(), name="creditcard_update"),
	path("creditcards/<int:pk>/delete/", views.CreditCardDelete.as_view(), name="creditcard_delete"),
	
	path("orders/", views.OrderList.as_view(), name="order_index"),
	path("orders/create/<int:shop_id>", views.OrderCreate.as_view(), name="order_start"),
	path("orders/<int:pk>/update/", views.OrderUpdate.as_view(), name="order_update"),
	path("orders/<int:pk>/delete/", views.OrderDelete.as_view(), name="order_delete"),
	path("orders/<int:pk>/", views.OrderDetail.as_view(), name="order_detail"),

	path("accounts/signup/", views.signup, name="signup"),
]

main_app/models.py
from django.db import models
from django.db.models.deletion import CASCADE
from django.urls import reverse
from django.conf import settings
# Django built-in User Model from auth
from django.contrib.auth.models import User

from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.
class Profile(models.Model):
    address = models.TextField(max_length=200)
    phone_number = models.CharField(max_length=11)
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.email
    
    def get_absolute_url(self):
        return reverse('user_detail', kwargs={ 'pk': self.id })

@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

class Shop(models.Model):
    name = models.CharField(max_length=200)
    address = models.TextField(max_length=200)
    phone_number = models.CharField(max_length=11)
    email = models.CharField(max_length=200)
    website = models.CharField(max_length=200)
    description = models.TextField(max_length=400)
    # shop_img = models.ImageField(upload_to=None, height_field=None, width_field=None, max_length=100)
    city = models.CharField(max_length=200)
    rating = models.DecimalField(max_digits=2, decimal_places=1)
    delivery_fee = models.DecimalField(max_digits=3, decimal_places=2)
    imgs = models.CharField(max_length=200, default=1)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop_detail', kwargs={ 'shop_id': self.id })

class IceCream(models.Model):
    SIZES = (
        ('S', "Small"),
        ('M', "Medium"),
        ('L', "Large"),
        ('T', "Tub")
    )
    flavor = models.CharField(max_length=200)
    shop = models.ForeignKey(Shop, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=3, decimal_places=2)
    # icecream_img = models.ImageField(upload_to=None, height_field=None, width_field=None, max_length=100)
    description = models.TextField(max_length=400)
    promotion = models.DecimalField(max_digits=3, decimal_places=2)
    size = models.CharField(
        max_length=1,
        choices=SIZES,
        default=SIZES[0][0]
    )

    def __str__(self):
        return self.flavor

    def get_absolute_url(self):
        return reverse('icecream_detail', kwargs={ 'pk': self.id })

class CreditCard(models.Model):
    card_number = models.CharField(max_length=200)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    address = models.TextField(max_length=200)
    security_code = models.CharField(max_length=4)
    exp_date = models.DateField()
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)

    def __str__(self):
        return self.card_number
    
    def get_absolute_url(self):
        return reverse('profile_detail')

class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    shop = models.ForeignKey(Shop, on_delete=models.CASCADE)
    creditcard = models.ForeignKey(CreditCard, on_delete=models.CASCADE)
    icecreams = models.ManyToManyField(IceCream, default='none')


    def __str__(self):
        return f"{self.user} at {self.shop}"
    
    def get_absolute_url(self):
        return reverse('order_detail', kwargs={ 'pk': self.id })

main_app/forms.py
from django import forms
from django.db.models import fields
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import CreditCard, Order

# modified sign up form for users to create a profile alongside a standard acct
class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=30)
    email = forms.EmailField(
        max_length=254,
        help_text="Enter an email address to receive digital receipts and promotion offers."
    )
    address = forms.CharField(
        max_length=200,
        help_text="Your address information is used to provide delivery services.",
    )
    phone_number = forms.CharField(
        max_length=11,
        help_text="Your phone number allows drivers to contact you if needed.",
    )

    class Meta:
        model = User
        fields = {
            'username', 
            'password1', 
            'password2', 
            'first_name', 
            'last_name', 
            'email', 
            'address', 
            'phone_number'
        }
    
    field_order = [
        'username', 
        'password1', 
        'password2', 
        'first_name', 
        'last_name', 
        'email', 
        'address', 
        'phone_number'
    ]

class CreditCardForm(ModelForm):
  class Meta:
    model = CreditCard
    fields = ['card_number', 'security_code', 'exp_date']

class OrderForm(ModelForm):
    # user_id = forms.IntegerField(label="User ID")
    # shop_id = forms.IntegerField(label="Shop ID")

    class Meta:
        model = Order
        fields = "__all__"
        # fields = ['icecreams','creditcard']

main_app/views.py
from typing import List
from django.http import request
from django.http.response import HttpResponse
from django.shortcuts import redirect, render
from django.views.generic import (
	CreateView, 
	UpdateView, 
	DeleteView, 
	ListView, 
	DetailView
)
from .models import Profile, CreditCard, Order, Shop, IceCream
from django.db.models import Q
# from .forms import 
from django.contrib.auth import login, authenticate
# from django.contrib.auth.forms import UserCreationForm
from main_app.forms import SignUpForm, CreditCardForm
from main_app.forms import OrderForm
# decorator to enforce login for view functions
from django.contrib.auth.decorators import login_required
# class-based views require a mixin - classes can't have decorators
from django.contrib.auth.mixins import LoginRequiredMixin



# Create your views here.

# basic homepage
def home(request):
	return render(request, "home.html")

def about(request):
	return render(request, "about.html")

def signup(request):
	error_message = ""
	if request.method == "POST":
		form = SignUpForm(request.POST)
		if form.is_valid():
			user = form.save()
			# load the profile instance created by the signal
			user.refresh_from_db()
			user.profile.address = form.cleaned_data.get('address')
			user.profile.phone_number = form.cleaned_data.get('phone_number')
			user.save()
			raw_password = form.cleaned_data.get('password1')
			user = authenticate(username=user.username, password=raw_password)
			login(request, user)
			return redirect("profile_detail")
		else:
			error_message = "Invalid signup data - please try again"
	form = SignUpForm()
	return render(request, "registration/signup.html", { 
    	"form": form,
    	"error_message": error_message,
  	})

class SearchResultsView(ListView):
	model = Shop
	template_name = "search_shops.html"

	def get_queryset(self):
		query = self.request.GET.get("search")
		if not query :
			query = ""
		object_list = Shop.objects.filter(
			Q(name__icontains=query) | Q(city__icontains=query)
		)
		return object_list

class ShopList(ListView):
	model = Shop

def shop_details(request, shop_id):
	shop = Shop.objects.get(id=shop_id)
	flavors = IceCream.objects.filter(shop_id=shop_id)
	order = Order.objects.all()
	form = OrderForm()
	return render(request, 'main_app/shop_detail.html', {'shop': shop, 'flavors': flavors, 'order': order, 'form': form})

@login_required
def profile(request):
	creditcard_form = CreditCardForm()
	return render(request, 'main_app/profile_detail.html', { 
		'creditcard_form':creditcard_form
	})
	
# TODO: add profile updating
class ProfileUpdate(UpdateView):
	model = Profile
	fields = ["address", "phone_number"]

@login_required
def add_creditcard(request, profile_id):
	form = CreditCardForm(request.POST)
	if form.is_valid():
		new_creditcard = form.save(commit=False)
		new_creditcard.profile_id = profile_id
		new_creditcard.save()
	return redirect('profile_detail')

class OrderList(LoginRequiredMixin, ListView):
	def get_queryset(self):
		return Order.objects.filter(user_id=self.request.user.id)

class OrderDetail(LoginRequiredMixin, DetailView):
	model = Order

class OrderCreate(LoginRequiredMixin, CreateView):
	model = Order
	# fields = "__all__"
	fields = ['icecreams','creditcard']
	success_url = "/orders/"

	# custom form validator to add user and shop ids
	def form_valid(self, form):
		new_order = form.save(commit=False)
		new_order.user_id = self.request.user.id
		# grab shop ID from URL
		new_order.shop_id = self.request.resolver_match.kwargs['shop_id']
		new_order.save()
		return super().form_valid(form)

@login_required
def start_order(request, shop_id):
	flavors = IceCream.objects.filter(shop_id=shop_id)
	creditcards = CreditCard.objects.filter(profile_id=request.user.profile.id)
	return render(request, "main_app/order_form.html", {
		"shop_id": shop_id, 
		"user_id": request.user.id,
		"flavors": flavors,
		"creditcards": creditcards,
	})


class OrderUpdate(LoginRequiredMixin, UpdateView):
	model = Order
	fields = ["icecreams", "creditcard"]
class OrderDelete(LoginRequiredMixin, DeleteView):
	model = Order
	success_url = "/orders/"


class CreditCardUpdate(LoginRequiredMixin, UpdateView):
	model = CreditCard
	fields = ["card_number", "security_code", "exp_date"]
class CreditCardDelete(LoginRequiredMixin, DeleteView):
	model = CreditCard
	success_url = "/profile/"

main_app/templates/main_app/creditcard_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

	<h1 class="text-center mb-4">Delete Credit Card</h1>

	<p class="text-center">
		Are you sure you want to delete card 
			<span style="color: lightgreen">{{ object }}</span>?
	</p>

	<div class="text-center">
		<form action="" method="POST">
			{% csrf_token %}
			<input 
				class="btn btn-danger" 
				type="submit" 
				value="Yes - Delete!"
			>
			<a 
				class="btn btn-secondary" 
				href="{% url 'profile_detail' %}"
			>
				No - Cancel
			</a>
		</form>
	</div>

{% endblock %}

main_app/templates/main_app/creditcard_form.html
{% extends 'base.html' %}

{% block content %}


	<h1 class="text-center mb-4">Edit Credit Card</h1>

	<div class="mx-auto card" style="max-width: 36rem;">
		<div class="card-body">
			<form action="" method="POST">
				{% csrf_token %}
				{{ form.as_p }}
				<input class="btn btn-primary" type="submit" value="Submit">
			</form>
		</div>
	</div>

	<script>
		const $labelEl = $("label");
		$labelEl.addClass("text-dark")
	</script>

{% endblock %}

main_app/templates/main_app/order_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

	<h1 class="text-center mb-4">Delete Order</h1>

	<p class="text-center">
		Are you sure you want to delete this order for 
			<span style="color: lightgreen">{{ object.shop }}</span>?
	</p>

	<div class="text-center">
		<form action="" method="POST">
			{% csrf_token %}
			<input 
				class="btn btn-danger" 
				type="submit" 
				value="Yes - Delete!"
			>
			<a 
				class="btn btn-secondary" 
				href="{% url 'order_detail' object.id %}"
			>
				No - Cancel
			</a>
		</form>
	</div>
	

{% endblock %}

main_app/templates/main_app/order_detail.html
{% extends "base.html" %}

{% block content %}

    <h1 class="text-center mb-4">Order Details</h1>
    <div class="card mx-auto" style="max-width: 36rem;">
        <div class="card-body">
            <h3 class="card-title text-center">{{ object }}</h3>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">
                <strong>Flavors: </strong>
                <ul>
                {% for flavor in object.icecreams.all %}
                    <li>{{ flavor }}</li>
                {% endfor %}
                </ul>
            </li>
            <li class="list-group-item">
                <strong>Credit Card:</strong>
                <br>
                {{ object.creditcard }}
            </li>
        </ul>
        <div class="card-body mx-auto">
            <a 
                class="card-link btn btn-success" 
                href="{% url 'order_update' order.id %}"
            >
                Edit Order
            </a>
            <a 
                class="card-link btn btn-danger" 
                href="{% url 'order_delete' order.id %}"
            >
                Delete Order
            </a>
        </div>
    </div>

{% endblock %}

main_app/templates/main_app/order_form.html
{% extends 'base.html' %}
{% block content %}

{% if object %}
	<h1 class="text-center mb-4">Edit Order: {{ object }}</span></h1>
{% else %}
	<h1 class="text-center mb-4">Create New Order</h1>
{% endif %}

	<div class="mx-auto card" style="max-width: 36rem;">
		<div class="card-body">
			<form action="" method="POST">
				{% csrf_token %}
				{{ form.as_p }}
				<input class="btn btn-primary" type="submit" value="Submit">
			</form>
		</div>
	</div>

<script>
    const $selectEl = $("#id_icecreams");
    $selectEl.addClass("form-select");

	const $labelEl = $("label");
	$labelEl.addClass("text-dark")
</script>

{% endblock %}

main_app/templates/main_app/order_list.html
{% extends "base.html" %}

{% block content %}

    <h1 class="text-center mb-4">Your Orders</h1>
    <div class="text-center">
    {% for order in object_list %}
        <div class="card mb-4 mx-auto" style="max-width: 36rem;">
            <div class="card-body">
                <a 
                    class="h4 link card-title" 
                    href="{% url 'order_detail' order.id %}"
                    style="color: #56A1B3;"
                >
                    {{ order }}
                </a>
                <div class="mt-2">
                    <a 
                        class="card-link btn btn-success" 
                        href="{% url 'order_update' order.id %}"
                    >
                        Edit Order
                    </a>
                    <a 
                        class="card-link btn btn-danger" 
                        href="{% url 'order_delete' order.id %}"
                    >
                        Delete Order
                    </a>
                </div>
            </div>
        </div>
    {% endfor %}
    </div>


{% endblock %}

main_app/templates/main_app/profile_detail.html
{% extends 'base.html' %}

{% block content %}
	
	<h1 class="text-center mb-4">Welcome, {{ user.username }}</h1>

	<div class="container">
		<div class="row">
			<div class="col-6 px-2 text-center">
				<h2 class="mb-4">Profile</h2>
				<p><strong>Location:</strong><br>{{ user.profile.address }}</p>
				<p><strong>Phone:</strong><br>{{ user.profile.phone_number }}</p>
				<a href="#" class="btn btn-primary">Edit Your Profile</a>
				<hr>
				<h2 class="text-center my-2">Checkout: ice cream is melting!</h2>
				<p>Check your recent orders here</p>
				<a href="{% url 'order_index' %}" class="btn btn-primary"> View Your Orders</a>
				<img src="../../static/images/cones.jpg" class="mt-4" alt="...">
			</div>
			<div class="col-6 px-2 text-center">
				<h2 class="mb-4">Payment Information</h2>
				<div class="accordion" id="card-accordion">
				{% for credit_card in user.profile.creditcard_set.all %}
					<div class="accordion-item">
						<h2 class="accordion-header" id="heading-{{ credit_card.id }}">
							<button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-{{ credit_card.id }}" aria-expanded="true" aria-controls="collapse-{{ credit_card.id }}">
								Credit Card
							</button>
						</h2>
						<div id="collapse-{{ credit_card.id }}" class="accordion-collapse collapse show" aria-labelledby="heading-{{ credit_card.id }}" data-bs-parent="#card-accordion">
							<div class="accordion-body">
								<p class="card-text">
									<strong>Card Number:</strong>
									<br>
									{{credit_card.card_number}}
								</p>
								<p class="card-text">
									<strong>Expiration Date:</strong>
									<br>
									{{credit_card.exp_date}}
								</p>
								<a class="btn btn-primary" href="{% url 'creditcard_update' credit_card.id %}">Edit</a>
								<a class="btn btn-warning" href="{% url 'creditcard_delete' credit_card.id %}">Delete</a>
							</div>
						</div>
					</div>
				{% endfor %}
				</div>

				<div class="mx-auto mt-4 card" style="max-width: 30rem;">
					<div class="card-body">
						<h4 class="card-title">Add a New Card</h4>
						<form action="{% url 'add_creditcard' user.profile.id %}" method="POST">
							{% csrf_token %}
							{{ creditcard_form.as_p }}
							<input class="btn btn-primary" type="submit" value="Submit">
						</form>
					</div>
				</div>

			</div>
		</div>
	</div>

	<script>
		const $selectEl = $("#id_icecreams");
		$selectEl.addClass("form-select");
	
		const $labelEl = $("label");
		$labelEl.addClass("text-dark")
	</script>

{% endblock %}

main_app/templates/main_app/shop_detail.html
{% extends 'base.html' %}

{% block content %}

    <h1 class="text-center mb-4">{{ shop.name }}</h1>
    <div class="item" style="background-image: url({{shop.imgs}});"></div>

    <div class="container text-center mt-4">
        <div class="row">
            <div class="col-6">
                <h3 class="mb-3" style= "color: rgb(209, 255, 176);">Menu</h3>
                {% for flavor in flavors %}
                    <h4 style="color: rgb(255, 255, 176);">{{ flavor }}</h4>
                    <p>{{ flavor.description }}</p>
                {% endfor %}
            </div>
            <div class="col-6">
                <h3 class="mb-3" style= "color: rgb(209, 255, 176);">Shop Details</h3>
                <p><strong>City:</strong> {{ shop.city }}</p>
                <p><strong>Phone:</strong> {{ shop.phone_number }}</p>
                <p><strong>Email:</strong> {{ shop.email }}</p>
                <p><strong>Website:</strong> {{ shop.website }}</p>
                <p><strong>Description:</strong> {{ shop.description }}</p>
            </div>
        </div>
    </div>

    <div class="mt-4 text-center">
        <h3>Ready to start your order?</h3>
        <a class="btn btn-info mt-2" href="{% url 'order_start' shop.id %}">Start an Order</a>
    </div>

{% endblock %}

main_app/templates/main_app/shop_list.html
{% extends 'home.html' %}
{% block content %}

    <h1 class="text-center mb-4">All Shops</h1>
    <div class="text-center">
    {% for shop in object_list %}
    <div class="card mb-4 mx-auto" style="max-width: 36rem;">
        <div class="card-body">
            <a class="h2 link card-title" href="/shops/{{ shop.id }}">
                {{ shop.name }}
            </a>
            <p class="card-text">
                {{ shop.description }}
            </p>
            <p class="card-text">
                City: {{ shop.city }}
                <br>
                Phone: {{ shop.phone_number }}
                <br>
                Email: {{ shop.email }}
                <br>
                Website: {{ shop.website }}
            </p>
            <a class="card-link btn btn-info" href="/shops/{{ shop.id }}">
                Visit Shop
            </a>
        </div>
    </div>
    {% endfor %}
    </div>

{% endblock %}